name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: alpine-gcc

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Extract metadata for Docker
      uses: docker/metadata-action@v3
      id: meta
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
    - name: Print metadata
      run: |
        echo "tags   : ${{ steps.meta.outputs.tags }}"
        echo "labels : ${{ steps.meta.outputs.labels }}"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.IMAGE }}/${{ steps.meta.outputs.tags }}
